rails/ror/config/routes.rb
Ror::Application.routes.draw do
  resources :cities

  resources :categories

  resources :phones

  resources :people

end

rails/ror/app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :category
  belongs_to :city
end

rails/ror/app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_filter :get_categories, 
    :only => [:edit, :create, :update, :new]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phones }
    end
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
    @phone = Phone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phone }
    end
  end

  # GET /phones/new
  # GET /phones/new.json
  def new
    @phone = Phone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phone }
    end
  end

  # GET /phones/1/edit
  def edit
    @phone = Phone.find(params[:id])
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(params[:phone])

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render json: @phone, status: :created, location: @phone }
      else
        format.html { render action: "new" }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phones/1
  # PUT /phones/1.json
  def update
    @phone = Phone.find(params[:id])

    respond_to do |format|
      if @phone.update_attributes(params[:phone])
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone = Phone.find(params[:id])
    @phone.destroy

    respond_to do |format|
      format.html { redirect_to phones_url }
      format.json { head :ok }
    end
  end

  private

  def get_categories
    @categories = Category.all.collect {|c| [c.name, c.id.to_i] }
  end

end

rails/ror/app/helpers/phones_helper.rb
module PhonesHelper
end

rails/ror/app/views/phones/_form.html.erb
<%= form_for(@phone) do |f| %>
  <% if @phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% @phone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :extension %><br />
    <%= f.number_field :extension %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.select :city_id, City.all.collect {|c| [c.name, c.id]} %><br />
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category_id, @categories %><br />
  </div>
  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.number_field :person_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/ror/app/views/phones/edit.html.erb
<h1>Editing phone</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

rails/ror/app/views/phones/index.html.erb
<h1>Listing phones</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Extension</th>
    <th>Category</th>
    <th>Person</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @phones.each do |phone| %>
  <tr>
    <td><%= phone.number %></td>
    <td><%= phone.extension %></td>
    <td><%= phone.category_id %></td>
    <td><%= phone.person_id %></td>
    <td><%= link_to 'Show', phone %></td>
    <td><%= link_to 'Edit', edit_phone_path(phone) %></td>
    <td><%= link_to 'Destroy', phone, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phone', new_phone_path %>

rails/ror/app/views/phones/new.html.erb
<h1>New phone</h1>

<%= render 'form' %>

<%= link_to 'Back', phones_path %>

rails/ror/app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @phone.number %>
</p>

<p>
  <b>Extension:</b>
  <%= @phone.extension %>
</p>

<p>
  <b>Category:</b>
  <%= @phone.category_id %>
</p>

<p>
  <b>Person:</b>
  <%= @phone.person_id %>
</p>


<%= link_to 'Edit', edit_phone_path(@phone) %> |
<%= link_to 'Back', phones_path %>